apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: hourly4yong1
  namespace: velero
spec:
  schedule: */10 * * * *
  template:
    includedNamespaces:
    - 'yong-postgresql'
    excludedNamespaces:
    includedResources:
    - '*'
    excludedResources:
    - storageclasses.storage.k8s.io
    includeClusterResources: null
    labelSelector:
      matchLabels:
        app: velero
        component: server
    snapshotVolumes: null
    storageLocation: default
    volumeSnapshotLocations:
      - default 
    ttl: 24h0m0s
status:
  phase: ""
  lastBackup:
  validationErrors:
